<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="11653" started-at="2018-07-03T12:08:44Z" finished-at="2018-07-03T12:08:55Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="11653" started-at="2018-07-03T12:08:44Z" finished-at="2018-07-03T12:08:55Z">
      <class name="com.olympics.Olympics">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.olympics.Olympics@5f341870]" name="setUp" is-config="true" duration-ms="10204" started-at="2018-07-03T12:08:44Z" finished-at="2018-07-03T12:08:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="step2()[pri:0, instance:com.olympics.Olympics@5f341870]" name="step2" duration-ms="581" started-at="2018-07-03T12:08:54Z" finished-at="2018-07-03T12:08:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- step2 -->
        <test-method status="FAIL" signature="step3_4()[pri:0, instance:com.olympics.Olympics@5f341870]" name="step3_4" duration-ms="520" started-at="2018-07-03T12:08:54Z" finished-at="2018-07-03T12:08:55Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.olympics.Olympics.step3_4(Olympics.java:53)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- step3_4 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.olympics.Olympics@5f341870]" name="tearDown" is-config="true" duration-ms="312" started-at="2018-07-03T12:08:55Z" finished-at="2018-07-03T12:08:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.olympics.Olympics -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
